name: red_social
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  shared_preferences: ^2.5.2
  firebase_core: ^2.24.2  # Necesario para inicializar Firebase
  cloud_firestore: ^4.15.5  # Base de datos Firestore
  firebase_auth: ^4.15.5  # Autenticación con Firebase

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
